name: Update README Stats

on:
  schedule:
    - cron: '0 0 * * *'   # tous les jours à minuit
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout le dépôt
      - uses: actions/checkout@v3

      # Installer Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '24'

      # Créer le dossier stats
      - run: mkdir -p stats

      # Générer les GitHub Stats
      - name: Generate GitHub Stats
        run: |
          curl -o stats/github-stats.svg "https://github-readme-stats.vercel.app/api?username=larakoto&show_icons=true&theme=tokyonight&count_private=true&hide_border=true&access_token=${{ secrets.GH_TOKEN }}"
          curl -o stats/top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=larakoto&layout=compact&theme=tokyonight&hide_border=true&count_private=true&access_token=${{ secrets.GH_TOKEN }}"

      # Commit et push les SVG
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stats/*.svg
          git commit -m "Update GitHub Stats" || echo "No changes to commit"
          git push
